version: '3.1'

services:

  redmine:
    image: redmine
    restart: always
    ports:
      - 8080:3000
    environment:
      REDMINE_DB_MYSQL: user_redmine
      REDMINE_DB_PASSWORD: redmine

  db:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: db_priscila
      MYSQL_DATABASE: priscila